/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by laravel-typescriptable
declare namespace App.Models {
  export interface Category {
    id: number
    user_id: number
    name: string
    type: string
    deleted_at?: string
    created_at?: string
    updated_at?: string
    type_view?: any
    user?: App.Models.User
  }
  export interface Transaction {
    id: number
    user_id: number
    category_id?: number
    from_asset_id: number
    to_asset_id?: number
    type: string
    date: string
    amount: number
    note?: string
    deleted_at?: string
    created_at?: string
    updated_at?: string
    type_view?: any
    user?: App.Models.User
    category?: App.Models.Category
    from?: App.Models.Asset
    to?: App.Models.Asset
  }
  export interface User {
    id: number
    image?: string
    name: string
    email: string
    email_verified_at?: string
    password: string
    remember_token?: string
    created_at?: string
    updated_at?: string
    initial?: any
    full_path_image?: any
    verified_at?: any
    notifications_count?: number
    roles_count?: number
    permissions_count?: number
    notifications?: any[]
    roles?: any[]
    permissions?: any[]
  }
  export interface Role {
    id: number
    name: string
    guard_name: string
    created_at?: string
    updated_at?: string
    permissions_count?: number
    users_count?: number
    permissions?: any[]
    users?: App.Models.User[]
  }
  export interface Setting {
    id: number
    app_name: string
    app_short_name: string
    app_version: string
    app_tagline?: string
    app_description: string
    seo_enabled: number
    meta_title: string
    meta_description: string
    meta_banner?: string
    meta_keywords: string
    meta_author: string
    app_logo?: string
    app_logo_dark?: string
    app_favicon?: string
    app_email?: string
    app_phone?: string
    app_whatsapp?: string
    app_facebook?: string
    app_instagram?: string
    app_twitter?: string
    app_tiktok?: string
    app_address?: string
    created_at?: string
    updated_at?: string
    full_path_banner?: any
    full_path_logo?: any
    full_path_logo_dark?: any
    full_path_favicon?: any
  }
  export interface Permission {
    id: number
    name: string
    guard_name: string
    created_at?: string
    updated_at?: string
    roles_count?: number
    users_count?: number
    permissions_count?: number
    roles?: any[]
    users?: App.Models.User[]
    permissions?: any[]
  }
  export interface Asset {
    id: number
    user_id: number
    name: string
    owner: string
    initial_value: number
    type?: string
    note?: string
    deleted_at?: string
    created_at?: string
    updated_at?: string
    type_view?: any
    user?: App.Models.User
  }
}

declare namespace App {
  export interface PaginateLink {
    url: string
    label: string
    active: boolean
  }
  export interface Paginate<T = any> {
    data: T[]
    current_page: number
    first_page_url: string
    from: number
    last_page: number
    last_page_url: string
    links: App.PaginateLink[]
    next_page_url: string
    path: string
    per_page: number
    prev_page_url: string
    to: number
    total: number
  }
  export interface ApiPaginate<T = any> {
    data: T[]
    links: {
      first?: string
      last?: string
      prev?: string
      next?: string
    }
    meta: {
      current_page: number
      from: number
      last_page: number
      links: App.PaginateLink[]
      path: string
      per_page: number
      to: number
      total: number
    }
  }
}
